#!/bin/bash
# DEPRECATED: Use cs2pov.json config file instead.
#
# Create a config:
#   cs2pov init
#
# Edit cs2pov.json with your jobs, then run:
#   cs2pov pov
#
# See cs2pov.json for the config format.

echo "This script is deprecated. Use 'cs2pov init' to create a cs2pov.json config,"
echo "then run 'cs2pov pov' to process all jobs."
exit 1
